### ISSUE TITLE
Internal server error when player try to use wooden cup on water block

### ISSUE THREAD

**Issue by ghost** [thetorine/thirstmod#2]
Client get kicked from server with internal server error

In the server console:

[19:59:44] [Server thread/WARN]: Failed to handle packet for /62.209.221.154:62337
java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77988_m(ItemStack.java:451) ~[add.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:929) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:722) [?:1.7.0_04-ea]
[19:59:44] [Server thread/INFO]: Kashaag lost connection: Internal server error

version 1.8.10 of TM

**Comment by thetorine** [comment]
Fixed.
